OZ-01-Team3/oz-main_project-fe

- app/globals.css
- app/page.tsx
- app/products/page.tsx
- components/Event.tsx
- components/Footer.tsx
- components/PageNation.tsx
> ### Title
> - [style] 전체상품페이지 css
> ### PR Type
> - 전체상품 페이지 css
> - Event 컴포넌트 분리, 
> - 페이지네이션 컴포넌트 생성
> - 페이지네이션 클래스명 너무 길어서 globals.css에 apply 해뒀어요
> - 가끔 css 변경할때마다 페이지가 날아가는것은 왜일까..
> [style] 전체상품페이지 css

- app/(auth)/sign-up/page.tsx
- tailwind.config.ts
> ### Title
>
> - [Style] 회원가입 스타일 
> ### PR Type
>
>
> - 회원가입 스타일 적용
> - tailwindcss.config.ts -> subGray 색상 추가
>
> - 없음.
> Style: 회원가입 스타일

- app/mypage/layout.tsx
- app/mypage/orderhistory/page.tsx
- components/OrderProducts.tsx
- components/SideNav.tsx
- orderProductData.ts
> ### Title
>
> - [Style] 주문이력 스타일
> ### PR Type
>
>
> - 마이페이지 사이드바 생성
> - 주문 이력페이지 
> - 디자인 배치가 조금 바뀌었습니다.
>
> Order history

- app/mypage/saleshistory/page.tsx
- components/SalesProducts.tsx
- components/SideNav.tsx
> ### Title
>
> - [style] 판매이력(대여상품) 스타일
>
>
> - 판매이력이라쓰고 대여상품이라 읽는다. 스타일 적용 그리고 sidenav 리팩토링 
>
> - x
> [style] Sales history

- app/wishList/page.tsx
> ### Title
> - [style] wishLIst 스타일링 구현
> ### PR Type
> - wishList 페이지 스타일링
> - 나 내 부분 다 했슈
> [style] wishLIst 스타일링 구현

- components/Footer.tsx
- tailwind.config.ts
> ### Title
> [style] footer 디자인
> ### PR Type
> - footer 스타일링
> - RootLayout 에 넣어뒀어요 이후에 로그인 상태에 따라서 렌더링 되도록 수정하면 될 듯 합니다.(로그인/회원가입 페이지에서는 안보이게)
> 룰루
> [style] footer 디자인

- app/chat/page.tsx
- components/Chat/Chat.tsx
- components/Chat/ChatBubble.tsx
- components/Chat/ChatInput.tsx
- components/Chat/ChatLIst.tsx
- components/Chat/ChatLists.tsx
- components/Chat/Chatting.tsx
- productDetailData.tsx
- tailwind.config.ts
> ### Title
> - [style] chat style refactor, chat response css
> ### PR Type
>
> - 채팅 페이지 수정
> - 채팅페이지 반응형 css
> - Tailwind.config.css 에 반응형 크기 추가
> - components/Chat/Chatting.tsx 파일 삭제
> 반응형확인해주쇼
> [style] chat style refactor, chat response css

- app/mypage/member-info/page.tsx
- components/AuthInput.tsx
- components/ChatNotification.tsx
- components/OrderProducts.tsx
- components/SalesProducts.tsx
- components/SideNav.tsx
> ### Title
>
> - [Refactor] 마이페이지 반응형, 사이드 네브바 링크 연결
> ### PR Type
>
>
> - 마이페이지 반응형, 사이드 네브바 링크 연결
>
> - 유저마다 가져오려면 나중에 슬러그 써야할것같기도
> Refactor: 마이페이지 반응형, 사이드 네브바 링크 연결

- app/chat/page.tsx
- app/globals.css
- components/Chat/Chat.tsx
- components/Chat/ChatAcceptModal.tsx
- components/Chat/ChatModal.tsx
- components/Chat/ChatRentalModal.tsx
> ### Title
> [style] 대여신청/수락하기 버튼 및 모달 디자인, input focus 스타일 수정
> ### PR Type
> - 대여신청하기/수락하기 버튼 디자인
> - 대여 신청/수락 모달 디자인
> - globals.css 에 input foucs시 아웃라인 없애는 스타일 추가
> - 글 올린 사람한테는 대여 신청하기 버튼 비활성화, 대여신청하는 사람한테는 수락하기 버튼 비활성화 예정
> [style] 대여신청/수락하기 버튼 및 모달 디자인, input focus 스타일 수정

- app/(auth)/sign-in/page.tsx
> ### Title
> [Feat] 로그인 페이지 기능 구현
> ### PR Type
> - 로그인 기능 구현
> - '아직 회원이 아니신가요?[Sign in]' 클릭 시 회원가입 페이지로 <Link>
> - FormData 삭제
> 200 성공일때 콘솔에 이메일만 뜨는게 원래 맞는걸까용
>  [Feat] 로그인 페이지 기능 구현

- app/search/page.tsx
- components/Search/History.tsx
- components/Search/SearchBar.tsx
- components/Search/SearchWord.tsx
> ### Title
>
> - [Style] 검색창 수정
> ### PR Type
>
>
> -  검색창 디자인 수정
>
> - x
> [Style] 검색창

- api/authRequests.ts
- api/instance.ts
- app/(auth)/sign-up/page.tsx
- app/layout.tsx
- components/CommonButton.tsx
- package.json
- yarn.lock
> ### Title
>
> - [feat] 회원가입 기능 구현
> ### PR Type
>
>
> - commonButton 타입 추가 
> - 이메일 발송, 인증 기능
> - 회원가입 
> - 토스티파이 라이브러리 설치
>
> - next.js에서 env 환경변수.. 안먹힘 이건 찾아봐야할듯
> - 이미 있는 회원은 어떤 코드 내려주는지 몰라잉.. 이것도 나중에 수정
> - 이미 회원가입한 이메일은 이메일 코드조차 안보내지는데 400코드 그대로 받아서 .. 처리하면 되는걸까...?
> [feat] 회원가입 기능 구현

- app/(auth)/sign-in/page.tsx
- app/(auth)/sign-up/page.tsx
> ### Title
>
> - [feat] 로그인
> ### PR Type
>
> - [x] CONF: 빌드, 환경 설정
>
> - 로그인 기능 구현
> - env 설정
>
> - 지금은 로그인해도 헤더 상태 변경 1도 안됩니다.....
> - 나중에 전역으로 회원상태 불러와서 관리해야할덧
> [feat] 로그인

- package.json
- src/api/instance.ts
- src/components/MSWComponent.tsx
- src/pages/auth/signIn.tsx
- src/pages/auth/signUp.tsx
> ### Title
>
> - [Chore]: 인터셉터 추가, 경로변경
> ### PR Type
>
>
> - 토큰인터셉터, 경로 변경했읍니다
>
> - x
> Chore: 인터셉터 추가, 경로변경

- package.json
- src/api/authRequests.ts
- src/components/ChatNotification.tsx
- src/components/Header.tsx
- src/components/chat/ChatComponent.tsx
- src/components/chat/ChatInput.tsx
- src/components/chat/ChatList.tsx
- src/components/chat/ChatLists.tsx
- src/pages/chat.tsx
- src/stores/useMessageStore.ts
- yarn.lock
> ### Title
>
> - [Refactor] 채팅
> ### PR Type
>
> - chatList 에러 바운더리 사용
> - 채팅 나가기 css
> - 채팅방 아이디 비교해서 채팅방마다 메세지 구분
> - 헤더 로고 클릭시 메인 화면으로 이동
>
> - x
> [Refactor] 채팅

- package.json
- src/components/SalesProducts.tsx
- src/components/chat/ChatList.tsx
- src/mocks/handlers.ts
- src/orderProductData.ts
- src/pages/chat.tsx
- src/pages/mypage/productRegistration.tsx
- src/stores/useMessageStore.ts
> ### Title
>
> - Chore: 타입 수정
> ### PR Type
>
>
> - 타입 수정
> - 
>
> - x
> Chore: 타입 수정

- package.json
- src/App.tsx
- src/api/chatRequests.ts
- src/components/Banner.tsx
- src/components/EventBanner.tsx
- src/components/Loading.tsx
- src/components/SalesProducts.tsx
- src/components/chat/ChatComponent.tsx
- src/components/chat/ChatDeleteModal.tsx
- src/components/chat/ChatInput.tsx
- src/components/chat/ChatList.tsx
- src/components/chat/ChatLists.tsx
- src/components/chat/ChatModal.tsx
- src/pages/chat.tsx
- src/stores/useUserInfoStore.ts
- tailwind.config.ts
- yarn.lock
> ### Title
>
> - Feat: 채팅방 나가기
> ### PR Type
>
>
> - 채팅방 나가기 기능 구현
> - 채팅 리스트 api 통신 코드 리액트쿼리로 변경
> - 채팅 전송시 보내는 사람 닉네임 추가, 이미지 사이즈 리사이징
> - 채팅방 나가기 클릭시 웹소켓 종료
>
> - 마지막 채팅방을 나갈경우에 바로 사라지지 않음. 추후 수정해야함
> Feat: 채팅방 나가기

- src/App.tsx
- src/pages/mypage/productRegistration.tsx
> ### Title
> [Fix 오류수정]
> ### PR Type
> 머지 후 오류 수정
> [Fix 오류수정]

- src/api/instance.ts
- src/components/Header.tsx
- src/components/chat/ChatComponent.tsx
- src/components/chat/ChatList.tsx
- src/components/chat/ChatLists.tsx
- src/pages/auth/signIn.tsx
- src/pages/chat.tsx
- src/pages/loginHandler.tsx
- src/pages/mypage/productRegistration.tsx
- src/stores/useAuthStore.ts
- src/stores/useMessageStore.ts
- src/type.ts
> ### Title
>
> - Feat: 네이버 소셜 로그인
> ### PR Type
>
>
> - 인스턴스 인터셉터 코드 수정
> - 로그인시 로그인 상태 반영 바로 안되는거 수정
> - 필드 수정
> - 네이버 소셜 로그인 핸들러 추가
> - useAuthStore 타입 추가
> - 로그인 바로 되는거 반영하니까 로그아웃하면 또 바로 반영안됨 이슈.. 로그아웃 구현까지하고 해결봐야할듯
> Feat: 네이버 소셜 로그인

- src/components/Products.tsx
- src/components/productDetail/ProductDetailModal.tsx
- src/components/productDetail/ProductDetailResponse.tsx
- src/components/search/SearchBar.tsx
- src/pages/auth/signIn.tsx
- src/pages/main.tsx
- src/pages/products/totalProducts.tsx
- src/pages/search.tsx
- src/pages/wishList.tsx
> ### Title
> [feat] wishList 기능구현
> ### PR Type
> - product 타입에 is_liked 추가
> - 하트 클릭 시 좋아요 기능 추가
> - 로그인 상태에 따라 상품 호출 api 수정 (로그인 안한 사용자는 wishList 체크 안되어있고, 로그인 한 사용자는 체크되어있도록)
> - wish-list에서 상품 상세 모달 열리고 닫힐때 라우팅 설정
> handleModalClose 같은 함수는 나중에 Utils 로 따로 뺄 예정 + 상품 조건부 호출도 instance 로 해볼게용....
> [feat] wishList 기능구현

- src/components/chat/ChatComponent.tsx
- src/components/productDetail/ProductDetailModal.tsx
- src/components/productDetail/ProductDetailsDescription.tsx
- src/stores/useProductDetailStore.ts
> ### Title
>
> - feat: 채팅방 연결
> ### PR Type
>
>
> - useProductDetailStore 생성
> - 상품 디테일에서 1:1 채팅버튼 클릭시 채팅방 생성
> - 채팅 버튼 누를때 상품 정보도 같이 넘겨줌
>
> - 동일한 pk로 채팅방 만드는데 채팅 버튼 누르는 족족 채팅방이 만들어짐
> - 상품정보 한번만 불러오고 새로고침하면 홀라당 사라짐
> - 추후 수정해야함...
> feat: 채팅방 연결

- src/App.tsx
- src/api/authRequests.ts
- src/api/instance.ts
- src/components/AuthInput.tsx
- src/components/Footer.tsx
- src/components/Header.tsx
- src/components/chat/ChatDeleteModal.tsx
- src/components/mypage/WithdrawalModal.tsx
- src/components/productDetail/ProductDetailsDescription.tsx
- src/pages/auth/signIn.tsx
- src/pages/auth/signUp.tsx
- src/pages/loginHandler.tsx
- src/pages/mypage/memberInfo.tsx
- src/pages/products/ProductUpdate.tsx
- src/pages/products/productRegistration.tsx
> ### Title
>
> - Feat: 내정보 관련 기능
> ### PR Type
>
>
> - Header.tsx -> 로그아웃 상태 반영 바로 안되는거 수정
> - AuthInput.tsx -> disabled 속성 추가
> - App.tsx -> 쿠키 가져오는 코드 수정, GetmemberResponseType, UserType profile -> profile_img로 필드 변경
> - authRequests.ts -> 회원수정 타입 추가, 토큰 리프레시 주석 삭제, 회원정보 수정 api코드 생성,modificationUserInfoType 타입 수정
> - instance.ts -> getCookieValue 코드 추가
> - ChatDeleteModal.tsx -> 뒷배경 색상 변경 
> - memberInfo.tsx -> 회원 탈퇴, 회원 정보 수정, 사진 업로드
>         WithdrawalModal.tsx 생성
> - signUp.tsx -> 보내는 데이터 수정
> - 액세스 토큰 쿠키 약어 수정
> - Footer.tsx -> 폰트 크기 수정
> - …
> Feat: 내정보 관련 기능

- src/pages/main.tsx
> ### Title
> [fix] localStorage 오류 수정
> ### PR Type
>
> - 로컬스토리지에 값 없을 시 예외처리
> [fix] localStorage 오류 수정

- src/pages/main.tsx
> ### Title
> [fix:모달 버그 수정]
> ### PR Type
>
> - [x] DOCS: 문서 추가 및 수정
> 로컬에 값 없을 시에 오류 수정
>
> [fix:모달 버그 수정]

- src/components/chat/ChatComponent.tsx
> ### Title
>
> - fix: 채팅 정렬 메세지 없을경우 수정
> ### PR Type
>
>
> - 채팅 정렬 메세지 없을경우 수정
> -
>
> - x
> fix: 채팅 정렬 메세지 없을경우 수정

- src/index.css
> ### Title
> - [feat] 스크롤바 안보이게 수정
> ### PR Type
>
> -  [feat] 스크롤바 안보이게 수정
> [feat] 스크롤바 안보이게 수정

- src/pages/auth/signIn.tsx
- src/pages/loginHandler.tsx
> ### Title
>
> - 제목은 '[Feat] 홈 페이지 구현'과 같이 작성합니다.
> ### PR Type
>
>
> - 구체적인 작업 내용을 작성해주세요.
> - 이미지를 별도로 첨부하면 더 좋습니다 👍
>
> 구글 로그인 버그 수정

- src/components/Banner.tsx
- src/components/EventBanner.tsx
- src/components/mypage/MyCloset.tsx
- src/components/productDetail/ProductDetailModal.tsx
- src/components/productDetail/ProductDetailResponse.tsx
- src/index.css
- src/pages/mypage/myCloset.tsx
- src/pages/products/ProductUpdate.tsx
- src/pages/products/productRegistration.tsx
> ### Title
> - [chore] 상품 삭제, 이미지 경로 수정, mypage 모달 경로 수정, textarea 크기 변경원
> ### PR Type
> - 상품 삭제
> -  이미지 경로 수정
> - mypage 모달 경로 수정
> - textarea 크기 변경원
>
> [chore] 상품 삭제, 이미지 경로 수정, mypage 모달 경로 수정, textarea 크기 변경원

- src/App.tsx
- src/NotificationContext.tsx
- src/components/Header.tsx
- src/components/Notification.tsx
- src/components/chat/ChatComponent.tsx
- src/components/chat/ChatInput.tsx
- src/components/chat/ChatLists.tsx
- src/components/productDetail/ProductDetailsDescription.tsx
- src/pages/chat.tsx
- src/pages/products/productRegistration.tsx
- src/stores/useNotificationStore.ts
cation 파일 이름 수정
> ### Title
>
> - Chore: 자잘한 버그 수정
> ### PR Type
>
>
> - 자잘한 버그 수정
>
> - x
> Chore: 자잘한 버그 수정

- src/pages/products/ProductUpdate.tsx
- src/pages/products/productRegistration.tsx
> ### Title
>
> - fix: 코드 수정
> ### PR Type
>
> - [X] FIX: 버그 수정
>
> - 수정 이전으로 돌아간 코드 복구
>
> x
> fix: 코드 수정

- src/App.tsx
- src/components/Header.tsx
- src/components/Products.tsx
- src/components/StyleModal.tsx
- src/components/chat/ChatAcceptModal.tsx
- src/components/chat/ChatComponent.tsx
- src/components/chat/ChatModal.tsx
- src/components/chat/ChatRentalModal.tsx
- src/components/mypage/OrderRentalHistorys.tsx
- src/components/productDetail/ProductDetailModal.tsx
- src/pages/main.tsx
- src/pages/mypage/salesHistory.tsx
- src/pages/products/ProductUpdate.tsx
- src/pages/products/productRegistration.tsx
- src/stores/useRentalStore.ts
> ### Title
> - [feat: 상품 대여,확정 기능 구현 및 오류 수정]
> ### PR Type
>
> - 상품 대여 신청 및 수락 기능 구현,
> - 헤더에 채팅 링크 추가 
> - 메인 페이지에 스타일 태그 추가 
> - 상품 등록,수정할 때 구매시기가 오늘보다 나중으로 선택 못하게 수정
> - useRentalStore 추가
>
> - 해치웠나 ..
> [feat: 상품 대여,확정 기능 구현 및 오류 수정]

- src/App.tsx
- src/NotificationContext.tsx
- src/api/instance.ts
- src/api/productRequest.ts
- src/components/Products.tsx
- src/components/StyleModal.tsx
- src/components/chat/ChatAcceptModal.tsx
- src/components/chat/ChatComponent.tsx
- src/components/chat/ChatList.tsx
- src/components/chat/ChatLists.tsx
- src/components/chat/ChatRentalModal.tsx
- src/components/mypage/OrderRentalHistorys.tsx
- src/components/productDetail/ProductDetailModal.tsx
- src/components/productDetail/ProductDetailResponse.tsx
- src/components/productDetail/ProductDetailsDescription.tsx
- src/components/search/SearchBar.tsx
- src/pages/auth/signIn.tsx
- src/pages/auth/signUp.tsx
- src/pages/chat.tsx
- src/pages/main.tsx
- src/pages/mypage/memberInfo.tsx
- src/pages/mypage/myCloset.tsx
- src/pages/mypage/salesHistory.tsx
- src/pages/products/ImageUpdate.tsx
- src/pages/products/ProductUpdate.tsx
- src/pages/products/imgRegistration.tsx
- src/pages/products/productRegistration.tsx
- src/pages/products/totalProducts.tsx
- src/pages/wishList.tsx
> ### Title
>
> - chore: 콘설 주석 추가
> ### PR Type
>
> -[x] CHORE: 기타 작업
>
> - 콘솔 삭제
> -
>
> -
> chore: 콘솔 주석 

- package.json
> ### Title
>
> - 제목은 '[Feat] 홈 페이지 구현'과 같이 작성합니다.
> ### PR Type
>
>
> - 구체적인 작업 내용을 작성해주세요.
> - 이미지를 별도로 첨부하면 더 좋습니다 👍
>
> Fix: 프록시 제거

- src/pages/loginHandler.tsx
> ### Title
>
> - 제목은 '[Feat] 홈 페이지 구현'과 같이 작성합니다.
> ### PR Type
>
- api/instance를 가져와서 요청보내도록 변경원
>
> Fix: 소셜로그인 수정

- src/components/productDetail/ProductDetailResponse.tsx
- src/pages/loginHandler.tsx
- src/pages/products/ProductUpdate.tsx
- src/pages/products/productRegistration.tsx
> ### Title
>
> - [Fix] 상품 카테고리 선택 시, 제일 기본값 설정 안하면 값 안들어가는 오류 수정
> ### PR Type
>
> 
> - 데이터 받아온 후에 처음 배열을 빈 값으로 추가해서 수정하였음! 
> - 빈배열로 안넣어줘도 Defaultvalue 값으로 설정할 수 있지 않았나 .. DefaultValue 랑 DefaultChecked 해줬는데도 안되더라고요 흠흠~
> [Fix] 상품 카테고리 선택 시, 기본값 설정 안하면 값 안들어가는 오류 수정
